name: Build
on:
  push:
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Configure
        uses: threeal/cmake-action@v1.3.0

      - name: Build 
        run: cmake -S . -B build && cmake --build build

      - name: Run tests
        run: cd build && ctest
